"""Generate fallback OpenMoHAA config and loose UI menu files."""

from __future__ import annotations

from pathlib import Path

from .commands import CONFIG_NAME, DEMO_COMMAND_NAME, MENU_NAME


def build_config_text(xray_enabled: bool = False) -> str:
    lines = [
        "// Generated by MoH Arena Demo Reviewer.",
        "// Primary control path is com_pipefile; these binds are fallbacks.",
        'seta cheats "1"',
        'seta sv_cheats "1"',
        'seta cl_freezeDemo "0"',
        'seta timescale "1"',
        'seta cg_3rd_person "0"',
    ]
    if xray_enabled:
        lines.extend(
            [
                "",
                "// X-ray review defaults.",
                'seta cg_forceModel "0"',
                'seta dm_playermodel "american_army"',
                'seta dm_playergermanmodel "german_wehrmacht_soldier"',
            ]
        )
    lines.extend(
        [
            "",
            'bind F5 "set timescale 0.0001; set cl_freezeDemo 1"',
            'bind F6 "set timescale 1; set cl_freezeDemo 0"',
            'bind F7 "toggle cg_3rd_person"',
            f'bind F8 "demo {DEMO_COMMAND_NAME}"',
            'bind F9 "screenshot"',
            f'bind F10 "togglemenu {MENU_NAME}"',
            'bind TAB "+scores"',
            "",
        ]
    )
    return "\n".join(lines)


def build_autoexec_text() -> str:
    return "\n".join(
        [
            "// Generated by MoH Arena Demo Reviewer.",
            f"exec {CONFIG_NAME}",
            f'bind F10 "togglemenu {MENU_NAME}"',
            "",
        ]
    )


def _button(title: str, name: str, x: int, y: int, command: str) -> str:
    return f"""resource
Button
{{
name "{name}"
title "{title}"
textalign centerx
rect {x} {y} 145 28
font facfont-20
stuffcommand "{command}"
borderstyle "3D_BORDER"
bgcolor 0.05 0.05 0.05 0.85
fgcolor 0.95 0.95 0.95 1.00
clicksound "sound/mechanics/hit_notify.wav"
}}
"""


def build_menu_text() -> str:
    buttons = [
        ("Pause", "pause", "set timescale 0.0001; set cl_freezeDemo 1"),
        ("Play 1x", "play1", "set timescale 1; set cl_freezeDemo 0"),
        ("0.5x", "speed05", "set timescale 0.5; set cl_freezeDemo 0"),
        ("2x", "speed2", "set timescale 2; set cl_freezeDemo 0"),
        ("4x", "speed4", "set timescale 4; set cl_freezeDemo 0"),
        ("8x", "speed8", "set timescale 8; set cl_freezeDemo 0"),
        ("Third Person", "thirdperson", "toggle cg_3rd_person"),
        ("Scores", "scores", "+scores"),
        ("Restart", "restart", f"demo {DEMO_COMMAND_NAME}"),
    ]
    header = f"""menu "{MENU_NAME}" 340 365 FROM_TOP 0.2
virtualres 1
align centerx centery
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.00

resource
Label
{{
name "background"
rect 0 0 340 365
fgcolor 1.00 1.00 1.00 1.00
bgcolor 0.00 0.00 0.00 0.75
borderstyle "3D_BORDER"
}}

resource
Label
{{
name "title"
title "MoH Arena Demo Review"
textalign centerx
rect 18 14 304 28
font facfont-20
fgcolor 0.95 0.85 0.45 1.00
bgcolor 0.00 0.00 0.00 0.00
borderstyle "NONE"
}}

"""
    body = []
    for index, (title, name, command) in enumerate(buttons):
        column = index % 2
        row = index // 2
        body.append(_button(title, name, 18 + column * 158, 58 + row * 42, command))
    return header + "\n".join(body)


def write_review_files(main_dir: Path, xray_enabled: bool = False) -> tuple[Path, Path, Path]:
    main_dir.mkdir(parents=True, exist_ok=True)
    ui_dir = main_dir / "ui"
    ui_dir.mkdir(parents=True, exist_ok=True)

    config_path = main_dir / CONFIG_NAME
    autoexec_path = main_dir / "autoexec.cfg"
    menu_path = ui_dir / f"{MENU_NAME}.urc"

    config_path.write_text(build_config_text(xray_enabled=xray_enabled), encoding="utf-8")
    autoexec_path.write_text(build_autoexec_text(), encoding="utf-8")
    menu_path.write_text(build_menu_text(), encoding="utf-8")

    return config_path, autoexec_path, menu_path
